### ISSUE TITLE
fix build with recent binutils

### ISSUE THREAD

**Issue by doko42** [ggcov/ggcov#6]
the build with recent binutils (2.34) is fixed with the attached patch.

Note that the package is not ready for GCC 9 and GCC 10.

--- ggcov-0.9+20190314.orig/src/cov_bfd.C
+++ ggcov-0.9+20190314/src/cov_bfd.C
@@ -330,11 +330,11 @@ cov_bfd_t::dump_reloc(unsigned int idx,
 unsigned char *
 cov_bfd_section_t::get_contents(bfd_size_type *lenp)
 {
-    asection *sec = (asection *)this;
+    const asection *sec = (asection *)this;
     bfd_size_type size;
     unsigned char *contents;
 
-    size = bfd_section_size(sec->owner, sec);
+    size = bfd_section_size(sec);
     contents = get_contents(0, size);
     if (lenp != 0)
        *lenp = size;

**Comment by gnb** [comment]
Thanks Matthias!

I will merge something based on this patch soon.

Have you attempted to adjust the code for GCC 9 and 10?

**Comment by gnb** [comment]
Commit 232f66f4 in the gcc8-support branch contains a solution based on this patch, thanks @doko42
